export * from './configs'
export * from './items'

/**
 * Currency of the value of the event, in 3-letter ISO 4217 format
 * @see {@link https://en.wikipedia.org/wiki/ISO_4217#Active_codes Three letter currency codes}
 */
export type Currency = 'EUR' | 'JPY' | 'USN' | 'CNY' | 'INR' | 'KRW' | 'BRL' | 'CHF' | 'CHE' | 'CAD' | 'AUD' | (string & {})

export type EventNames =
  | 'add_payment_info'
  | 'add_shipping_info'
  | 'add_to_cart'
  | 'add_to_wishlist'
  | 'begin_checkout'
  | 'checkout_progress'
  | 'earn_virtual_currency'
  | 'exception'
  | 'generate_lead'
  | 'join_group'
  | 'level_end'
  | 'level_start'
  | 'level_up'
  | 'login'
  | 'page_view'
  | 'post_score'
  | 'purchase'
  | 'refund'
  | 'remove_from_cart'
  | 'screen_view'
  | 'search'
  | 'select_content'
  | 'select_item'
  | 'select_promotion'
  | 'set_checkout_option'
  | 'share'
  | 'sign_up'
  | 'spend_virtual_currency'
  | 'tutorial_begin'
  | 'tutorial_complete'
  | 'unlock_achievement'
  | 'timing_complete'
  | 'view_cart'
  | 'view_item'
  | 'view_item_list'
  | 'view_promotion'
  | 'view_search_results'
  | 'disqualify_lead'
  | 'working_lead'
  | 'close_convert_lead'
