name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: npm i -g --force corepack@latest && corepack enable
      - name: Install dependencies
        run: npx nypm@latest i
      - name: Install pnpm
        run: npm i -g pnpm@latest
      - name: Lint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: npm i -g --force corepack@latest && corepack enable
      - name: Install dependencies
        run: npx nypm@latest i
      - name: Install pnpm
        run: npm i -g pnpm@latest
      - name: Playground prepare
        run: pnpm run dev:prepare
      - name: Test
        run: pnpm run test
