# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'Deploy application to the specified environment'
#         required: true
#         default: 'production'
#         type: choice
#         options:
#           - production
#           - staging

on:
  pull_request:
    branches:
      - develop

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=24"

      - run: npm i -g --force corepack@latest && corepack enable

      - name: "Install dependencies"
        run: npx nypm@latest i

      - name: Install Nuxt
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
